# Generated by Django 3.1.4 on 2021-02-27 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_text',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='user',
            name='github_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
