# Generated by Django 3.1.4 on 2021-02-28 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210227_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='users/avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
