# Generated by Django 3.1.4 on 2021-02-28 15:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210228_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='users/avatars/default/default.png', upload_to='users/avatars'),
        ),
    ]
