# Generated by Django 3.1.4 on 2021-02-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210228_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatars/default/default.png', upload_to='users/avatars'),
        ),
    ]
