# Generated by Django 3.1.4 on 2021-03-01 00:13

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210228_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='users/avatars/default/default.jpg', upload_to='users/avatars'),
        ),
    ]
